### ISSUE TITLE
Bantu ngembangin project

### ISSUE THREAD

**Issue by rinaldipratama** [Faiznurullah/Rekam_Medis#1]
Gan, aku mau bantu ngembangin project ini, bolehkah? tapi ditambah topic hacktoberfest ya hehe 😅 ada beberapa security isu diprojectnya, biar ada kerjaan juga di masa Hacktoberfest ini wkwk.

**Comment by Faiznurullah** [comment]
Native euy ngga pp kah ?

**Comment by rinaldipratama** [comment]
gpp, aku udah sering buat program kayak ini hehe
